#!/bin/bash
set -e

# Function to detect Pi model
detect_pi_model() {
    if grep -q "Raspberry Pi.*5" /proc/cpuinfo 2>/dev/null; then
        echo "pi5"
    elif grep -q "Raspberry Pi.*4" /proc/cpuinfo 2>/dev/null; then
        echo "pi4"
    else
        echo "unknown"
    fi
}

case "$1" in
    configure)
        echo "Configuring PiTrac..."

        # Detect Pi model
        PI_MODEL=$(detect_pi_model)
        echo "Detected Pi model: $PI_MODEL"


        # Get the actual user who invoked sudo (if any)
        ACTUAL_USER="${SUDO_USER:-}"
        if [ -z "$ACTUAL_USER" ]; then
            echo "Note: Run 'pitrac setup' as your regular user to complete setup"
        else
            # Add user to required groups
            usermod -a -G video,gpio,i2c,spi,dialout "$ACTUAL_USER" 2>/dev/null || true

            # Create user directories
            USER_HOME=$(getent passwd "$ACTUAL_USER" | cut -d: -f6)
            if [ -n "$USER_HOME" ] && [ -d "$USER_HOME" ]; then
                mkdir -p "$USER_HOME/.pitrac"/{config,cache,state,calibration}
                mkdir -p "$USER_HOME/LM_Shares"/{Images,WebShare}
                chown -R "$ACTUAL_USER:$ACTUAL_USER" "$USER_HOME/.pitrac" "$USER_HOME/LM_Shares"

                # Copy default config to user directory if it doesn't exist
                if [ ! -f "$USER_HOME/.pitrac/config/pitrac.yaml" ]; then
                    cp /etc/pitrac/pitrac.yaml "$USER_HOME/.pitrac/config/pitrac.yaml"
                    chown "$ACTUAL_USER:$ACTUAL_USER" "$USER_HOME/.pitrac/config/pitrac.yaml"
                fi
            fi
        fi

        # System config should be root-owned and world-readable
        chown root:root /etc/pitrac
        chmod 755 /etc/pitrac
        chown root:root /etc/pitrac/pitrac.yaml
        chmod 644 /etc/pitrac/pitrac.yaml
        if [ -f /etc/pitrac/golf_sim_config.json ]; then
            chown root:root /etc/pitrac/golf_sim_config.json
            chmod 644 /etc/pitrac/golf_sim_config.json
        fi


        # Install Python web server dependencies
        if [ -d /usr/lib/pitrac/web-server ]; then
            echo "Installing Python web server dependencies..."
            pip3 install -r /usr/lib/pitrac/web-server/requirements.txt --break-system-packages 2>/dev/null || \
            pip3 install -r /usr/lib/pitrac/web-server/requirements.txt || true
        fi

        # Apply Boost C++20 fix
        if [ -f /usr/include/boost/asio/awaitable.hpp ] && ! grep -q "#include <utility>" /usr/include/boost/asio/awaitable.hpp; then
            echo "Applying Boost 1.74 C++20 compatibility fix..."
            sed -i '/namespace boost {/i #include <utility>' /usr/include/boost/asio/awaitable.hpp
        fi

        # Configure boot settings - Bookworm uses /boot/firmware for both Pi 4 and Pi 5
        if [ -f "/boot/firmware/config.txt" ]; then
            CONFIG_FILE="/boot/firmware/config.txt"
        elif [ -f "/boot/config.txt" ] && ! grep -q "DO NOT EDIT THIS FILE" /boot/config.txt 2>/dev/null; then
            CONFIG_FILE="/boot/config.txt"
        else
            # Default to new location
            CONFIG_FILE="/boot/firmware/config.txt"
        fi

        if [ -f "$CONFIG_FILE" ]; then
            echo "Configuring boot settings in $CONFIG_FILE..."

            # Add settings if not present
            grep -q "camera_auto_detect=1" "$CONFIG_FILE" || echo "camera_auto_detect=1" >> "$CONFIG_FILE"
            grep -q "dtparam=i2c_arm=on" "$CONFIG_FILE" || echo "dtparam=i2c_arm=on" >> "$CONFIG_FILE"
            grep -q "dtparam=spi=on" "$CONFIG_FILE" || echo "dtparam=spi=on" >> "$CONFIG_FILE"
            grep -q "force_turbo=1" "$CONFIG_FILE" || echo "force_turbo=1" >> "$CONFIG_FILE"

            if [ "$PI_MODEL" = "pi5" ]; then
                grep -q "arm_boost=1" "$CONFIG_FILE" || echo "arm_boost=1" >> "$CONFIG_FILE"
            else
                grep -q "gpu_mem=256" "$CONFIG_FILE" || echo "gpu_mem=256" >> "$CONFIG_FILE"
            fi
        fi

        # Configure libcamera settings
        echo "Configuring libcamera..."

        # Use existing example.yaml files as base for configuration
        # Both Pi 4 (vc4) and Pi 5 (pisp) ship with example.yaml
        for pipeline in pisp vc4; do
            CAMERA_DIR="/usr/share/libcamera/pipeline/rpi/${pipeline}"
            EXAMPLE_FILE="${CAMERA_DIR}/example.yaml"
            CAMERA_CONFIG="${CAMERA_DIR}/rpi_apps.yaml"

            # Only proceed if the pipeline directory exists (Pi 4 has vc4, Pi 5 has pisp)
            if [ -d "$CAMERA_DIR" ]; then
                # If example exists but rpi_apps doesn't, copy and configure
                if [ -f "$EXAMPLE_FILE" ] && [ ! -f "$CAMERA_CONFIG" ]; then
                    echo "Creating ${pipeline} config from example..."
                    cp "$EXAMPLE_FILE" "$CAMERA_CONFIG"
                    # Uncomment and set the camera timeout to 1 second (1000000 ms)
                    sed -i 's/# *"camera_timeout_value_ms": *[0-9]*/"camera_timeout_value_ms": 1000000/' "$CAMERA_CONFIG"
                elif [ -f "$CAMERA_CONFIG" ]; then
                    # Config exists, check if timeout needs updating
                    if grep -q '# *"camera_timeout_value_ms"' "$CAMERA_CONFIG"; then
                        echo "Updating ${pipeline} camera timeout..."
                        sed -i 's/# *"camera_timeout_value_ms": *[0-9]*/"camera_timeout_value_ms": 1000000/' "$CAMERA_CONFIG"
                    fi
                fi
            fi
        done
        # Update library cache
        ldconfig

        # Reload systemd
        systemctl daemon-reload

        # Configure ActiveMQ
        if command -v activemq &>/dev/null || [ -f /usr/share/activemq/bin/activemq ]; then
            echo "Configuring ActiveMQ for PiTrac..."
            
            if [ -x /usr/lib/pitrac/activemq-service-install.sh ]; then
                echo "Installing ActiveMQ configuration from templates..."
                export ACTIVEMQ_BROKER_NAME="localhost"
                export ACTIVEMQ_BIND_ADDRESS="127.0.0.1"
                export ACTIVEMQ_PORT="61616"
                export ACTIVEMQ_LOG_LEVEL="INFO"
                export PITRAC_TEMPLATE_DIR="/usr/share/pitrac/templates"
                
                if /usr/lib/pitrac/activemq-service-install.sh install activemq; then
                    echo "ActiveMQ configuration installed successfully"
                else
                    echo "Warning: ActiveMQ configuration failed, falling back to basic setup"
                    mkdir -p /etc/activemq/instances-available/main
                    mkdir -p /etc/activemq/instances-enabled
                    if [ ! -e /etc/activemq/instances-enabled/main ]; then
                        ln -sf /etc/activemq/instances-available/main /etc/activemq/instances-enabled/main
                    fi
                fi
            else
                echo "Warning: ActiveMQ configuration script not found, using basic setup"
                if [ -d /etc/activemq/instances-available ] && [ ! -e /etc/activemq/instances-enabled/main ]; then
                    mkdir -p /etc/activemq/instances-enabled
                    ln -sf /etc/activemq/instances-available/main /etc/activemq/instances-enabled/main
                fi
            fi
            
            if getent passwd activemq >/dev/null; then
                chown -R activemq:activemq /var/lib/activemq/ 2>/dev/null || true
            fi
            
            # Don't start it here - let the user or pitrac CLI handle it
        fi

        if [ -x /usr/lib/pitrac/service-install.sh ]; then
            if [ -n "$ACTUAL_USER" ]; then
                echo "Installing PiTrac service for user: $ACTUAL_USER"
                /usr/lib/pitrac/service-install.sh install "$ACTUAL_USER" || true
            else
                echo "Note: PiTrac service not installed. Run '/usr/lib/pitrac/service-install.sh install <username>' to install for a specific user"
            fi
        fi

        # Enable web server
        if [ -f /etc/systemd/system/pitrac-web.service ]; then
            # If we have an actual user, create a drop-in to override the user
            if [ -n "$ACTUAL_USER" ]; then
                mkdir -p /etc/systemd/system/pitrac-web.service.d
                cat > /etc/systemd/system/pitrac-web.service.d/override.conf <<EOF
[Service]
User=$ACTUAL_USER
Group=$ACTUAL_USER
DynamicUser=no
EOF
            fi
            systemctl enable pitrac-web.service || true
        fi

        echo ""
        echo "======================================"
        echo " PiTrac installed!"
        echo "======================================"
        echo ""
        echo "Get started:"
        echo "  pitrac setup    - Set up your directories"
        echo "  pitrac test     - Check your cameras"
        echo "  pitrac run      - Start tracking shots"
        echo ""
        echo "The broker and web server start automatically when you run PiTrac."
        echo ""
        echo "Need help? Try 'pitrac help' or 'pitrac status'"
        echo ""

        # Suggest reboot if Pi model detected
        if [ "$PI_MODEL" != "unknown" ]; then
            echo "Note: A reboot is recommended to apply boot configuration changes."
        fi
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument: $1" >&2
        exit 1
        ;;
esac

exit 0